### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jatin99** [mapbox/tilemill#2563] opened 2016-07-08 08:14 UTC
Node Version 	v4.4.7
Npm Version 

I am trying to run protractor in my bamboo environment. So in my script task configuration I run the script 
node_modules/.bin/protractor mapfeedback-spec.js

when I try t run my plan I get the following error : 
	SyntaxError: Use of const in strict mode.
08-Jul-2016 08:14:01	    at Module._compile (module.js:439:25)
08-Jul-2016 08:14:01	    at Object.Module._extensions..js (module.js:474:10)
08-Jul-2016 08:14:01	    at Module.load (module.js:356:32)
08-Jul-2016 08:14:01	    at Function.Module._load (module.js:312:12)
08-Jul-2016 08:14:01	    at Module.require (module.js:364:17)
08-Jul-2016 08:14:01	    at require (module.js:380:17)
08-Jul-2016 08:14:01	    at Object.<anonymous> (/devzone1/buildfarm/sadvzpbld04/bamboo-agent-home/xml-data/build-dir/RDMPDEV-MAP-JOB1/node_modules/protractor/built/driverProviders/driverProvider.js:8:17)
08-Jul-2016 08:14:01	    at Module._compile (module.js:456:26)
08-Jul-2016 08:14:01	    at Object.Module._extensions..js (module.js:474:10)
08-Jul-2016 08:14:01	    at Module.load (module.js:356:32)

**Comment by tmcw** [comment] 2016-07-21 12:48
Closing as duplicate of #2541

**Closed by tmcw** 2016-07-21 12:48 UTC
