### ISSUE TITLE
Error: Filename may include alphanumeric characters, dashes and underscores.

### ISSUE THREAD

**Issue by mpxixi** [mapbox/tilemill#2411] opened 2014-09-21 11:26 UTC

**Comment by pnorman** [comment] 2015-01-30 00:50
No description was provided but the text "Error: Filename may include alphanumeric characters, dashes and underscores." should probably contain **only**.

**Comment by springmeyer** [comment] 2015-01-30 03:49
duplicate of #2042. This is fixed and will be live in the next release: https://github.com/mapbox/tilemill/milestones/0.10.2

**Closed by springmeyer** 2015-01-30 03:49 UTC
